# ===== BUILD =====
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copy csproj theo layer để cache restore
COPY ./Domain/NexusPM.Domain.csproj ./NexusPM.Domain/
COPY ./Application/NexusPM.Application.csproj ./NexusPM.Application/
COPY ./Infrastructure/NexusPM.Infrastructure.csproj ./NexusPM.Infrastructure/
COPY ./NexusPM.Api/NexusPM.Api.csproj ./NexusPM.Api/

RUN dotnet restore ./NexusPM.Api/NexusPM.Api.csproj

# copy toàn bộ source và publish
COPY . .
WORKDIR /src/NexusPM.Api
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# ===== RUNTIME =====
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "NexusPM.Api.dll"]